const concepts=[["Money","Money"],["Time Value of Money","Time Value of Money"],["Interest","Interest"],["Simple Interest","Simple Interest"],["Compound Interest","Compound Interest"],["Inflation","Inflation"],["Interest Rate","Interest Rate"],["Present Value (PV)","Present Value"],["Future Value (FV)","Future Value"],["Discount Rate","Discount Rate"],["Investment","Investment"],["Return","Return"],["Risk","Risk"],["Risk and Return","Risk and Return"],["Asset","Asset"],["Stock","Stock"],["Bond","Bond"],["Dividend","Dividend"],["Capital Gain","Capital Gain"],["Portfolio","Portfolio"],["Diversification","Diversification"],["Liquidity","Liquidity"],["Market","Market"],["Supply and Demand","Supply and Demand"],["Bull Market","Bull Market"],["Bear Market","Bear Market"],["Market Capitalization","Market Capitalization"],["Stock Index","Stock Index"],["GDP (Gross Domestic Product)","Gross Domestic Product"],["Central Bank","Central Bank"]];
const $=id=>document.querySelector(id), stages={draw:$("#drawStage"),learn:$("#learnStage"),output:$("#outputStage"),review:$("#reviewStage")};let selectedHours=0,selectedMinutes=15,selectedSeconds=0,outputHours=0,outputMinutes=3,outputSeconds=0,remaining=900,timerId=null,endAt=0,outputId=null,outputEnd=0,mediaRecorder=null,chunks=[],recognition=null,recognitionShouldRun=false,currentConcept="",currentEnglish="";
const memoryKey="financePracticeMemory";let memories=JSON.parse(localStorage.getItem(memoryKey)||"[]");
function show(name){Object.entries(stages).forEach(([k,e])=>e.classList.toggle("hidden",k!==name));document.querySelectorAll("[data-stage]").forEach(e=>e.classList.toggle("active",e.dataset.stage===name));window.scrollTo({top:0,behavior:"smooth"})}
// Register the primary action before optional modules initialize.
$("#drawButton").addEventListener("click",()=>{const available=concepts.filter(c=>!memories.some(m=>m.english===c[0]));const pool=available.length?available:concepts;const c=pool[Math.floor(Math.random()*pool.length)];currentEnglish=c[0];currentConcept=c[1];$("#conceptEnglish").textContent=c[0];$("#conceptChinese").textContent=c[1];show("learn")});
function alarm(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C();[0,.55,1.1].forEach((d,i)=>{const o=c.createOscillator(),g=c.createGain();o.type="sine";o.frequency.value=[523,659,784][i];g.gain.setValueAtTime(.001,c.currentTime+d);g.gain.linearRampToValueAtTime(.16,c.currentTime+d+.08);g.gain.linearRampToValueAtTime(.001,c.currentTime+d+.48);o.connect(g).connect(c.destination);o.start(c.currentTime+d);o.stop(c.currentTime+d+.52)})}
function fmt(s){return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(v=>String(Math.max(0,v)).padStart(2,"0")).join(":")}
function wheel(el,max,val,set){el.innerHTML="";for(let i=0;i<=max;i++){const d=document.createElement("div");d.className="wheel-option"+(i===val?" selected":"");d.textContent=String(i).padStart(2,"0");d.onclick=()=>set(i);el.append(d)}requestAnimationFrame(()=>el.children[val]?.scrollIntoView({block:"center"}));let pending;el.onscroll=()=>{clearTimeout(pending);pending=setTimeout(()=>{const i=Math.min(max,Math.max(0,Math.round(el.scrollTop/44)));if(i!==val){el.querySelectorAll(".wheel-option").forEach(x=>x.classList.remove("selected"));el.children[i].classList.add("selected");set(i)}},120)}}
function renderDeck(target){const editor=$("#slideEditor"),container=$(target);if(!editor||!container)return;container.innerHTML=[...editor.querySelectorAll(".slide-page")].map((page,i)=>{const content=page.innerHTML.replace(/<small>[\s\S]*?<\/small>|<button[\s\S]*?<\/button>/g,"");return `<article class="slide-mini"><small>Page ${String(i+1).padStart(2,"0")}</small>${content}</article>`}).join("")}
function addSecondsWheel(baseId,id){const base=$(baseId);if(!base)return null;const el=document.createElement("div");el.className="wheel-column";el.id=id;el.tabIndex=0;base.parentElement.append(el);return el}const learnSecondsWheel=addSecondsWheel("#minutesWheel","secondsWheel"),outputSecondsWheel=addSecondsWheel("#outputMinutesWheel","outputSecondsWheel");
function wheels(){wheel($("#hoursWheel"),12,selectedHours,v=>{selectedHours=v});wheel($("#minutesWheel"),59,selectedMinutes,v=>{selectedMinutes=v});wheel(learnSecondsWheel,59,selectedSeconds,v=>{selectedSeconds=v});wheel($("#outputHoursWheel"),12,outputHours,v=>{outputHours=v;updateOutputPreview()});wheel($("#outputMinutesWheel"),59,outputMinutes,v=>{outputMinutes=v;updateOutputPreview()});wheel(outputSecondsWheel,59,outputSeconds,v=>{outputSeconds=v;updateOutputPreview()})}function updateOutputPreview(){const s=outputHours*3600+outputMinutes*60+outputSeconds;$("#outputCountdown").textContent=fmt(s)}wheels();updateOutputPreview();
function finishLearn(){clearInterval(timerId);timerId=null;alarm();show("output")}
function updateLearn(){remaining=Math.max(0,Math.ceil((endAt-Date.now())/1000));$("#countdown").textContent=fmt(remaining);if(remaining<=0)finishLearn()}
$("#startTimerButton").onclick=()=>{const d=selectedHours*3600+selectedMinutes*60;if(!d)return;endAt=Date.now()+d*1000;$("#timerRunning").classList.remove("hidden");$(".timer-setup").classList.add("hidden");$("#pauseTimerButton").textContent="Pause";clearInterval(timerId);timerId=setInterval(updateLearn,250);updateLearn()};
$("#pauseTimerButton").onclick=()=>{if(timerId){clearInterval(timerId);timerId=null;remaining=Math.max(0,Math.ceil((endAt-Date.now())/1000));$("#pauseTimerButton").textContent="Resume"}else{endAt=Date.now()+remaining*1000;$("#pauseTimerButton").textContent="Pause";timerId=setInterval(updateLearn,250)}};
$("#resetTimerButton").onclick=()=>{clearInterval(timerId);timerId=null;remaining=selectedHours*3600+selectedMinutes*60;$("#countdown").textContent=fmt(remaining);$("#timerRunning").classList.add("hidden");$(".timer-setup").classList.remove("hidden")};
function outputTick(){const r=Math.max(0,Math.ceil((outputEnd-Date.now())/1000));$("#outputCountdown").textContent=fmt(r);return r}
function startOutput(onDone){const d=outputHours*3600+outputMinutes*60;if(!d)return false;outputEnd=Date.now()+d*1000;clearInterval(outputId);outputId=setInterval(()=>{if(outputTick()<=0){clearInterval(outputId);alarm();onDone?.()}},250);outputTick();return true}
function finish(text){clearInterval(outputId);$("#reviewText").value=text||"No transcript was generated for this presentation.";renderDeck("#reviewDeckPreview");$("#conceptExplanation").innerHTML=`<p><strong>${currentConcept}</strong> is today's finance concept. Strengthen your understanding through its definition, mechanism, real-world examples, and limits.</p><p>In your next review, consider which concepts it is often confused with and how it shapes real financial decisions.</p>`;const length=(text||"").trim().length;$("#presentationFeedback").innerHTML=`<p>Your transcript contains approximately ${length} characters.</p><p><strong>Strength:</strong> You completed a full spoken explanation and created a record to revisit.</p><p><strong>Next step:</strong> Start with a one-sentence definition, add one concrete example, then close with a limitation or risk.</p>`;show("review")}

$("#pptTemplate").onchange=()=>{const t=$("#pptTemplate").value;const pages=$("#slideEditor").querySelectorAll(".slide-page");const sets=t==="compare"?["Definition & traits","Strengths & limits","Case comparison"]:["Concept definition","Why it matters","Real-world example"];pages.forEach((p,i)=>{p.querySelector("h3").textContent=sets[i]});renderDeck("#learnSlidePreview")};$("#slideEditor").addEventListener("input",()=>renderDeck("#learnSlidePreview"));$("#slideEditor").addEventListener("click",e=>{if(!e.target.classList.contains("add-text"))return;const p=document.createElement("p");p.contentEditable="true";p.textContent="New content";e.target.before(p);p.focus()});$("#addSlideButton").onclick=()=>{const n=$("#slideEditor").querySelectorAll(".slide-page").length+1;const a=document.createElement("article");a.className="slide-page";a.innerHTML=`<small>Page ${String(n).padStart(2,"0")}</small><h3 contenteditable="true">New page title</h3><p contenteditable="true">Click to edit this page.</p><button class="text-button add-text" type="button">+ Add text box</button>`;$("#slideEditor").append(a);renderDeck("#learnSlidePreview")};renderDeck("#learnSlidePreview");
renderDeck("#outputDeckPreview");
$("#startVideoButton").onclick=async()=>{if(mediaRecorder?.state==="recording"){mediaRecorder.stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){$("#recordingStatus").textContent="当前浏览器不支持视频录制";return}let stream;try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true})}catch(e){$("#recordingStatus").textContent="无法访问摄像头或麦克风，请检查浏览器权限";return}const preview=$("#videoPreview");preview.srcObject=stream;preview.muted=true;preview.autoplay=true;preview.playsInline=true;preview.classList.remove("hidden");chunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);mediaRecorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());preview.srcObject=null;preview.src=URL.createObjectURL(new Blob(chunks,{type:"video/webm"}));preview.controls=true;$("#finishVideoButton").classList.remove("hidden");$("#recordingStatus").textContent="录制完成，语音转写已停止";recognitionShouldRun=false;recognition?.stop();if(mediaRecorder.autoFinish)finish($("#videoTranscript").value)};mediaRecorder.start();$("#startVideoButton").textContent="结束录制";$("#recordingStatus").textContent="正在录制并自动转写...";$("#videoTranscript").value="";let transcriptFinal="";const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(R){recognition=new R();recognition.lang="zh-CN";recognition.continuous=true;recognition.interimResults=true;recognition.maxAlternatives=1;recognition.onresult=e=>{let interim="";for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0].transcript;if(e.results[i].isFinal)transcriptFinal+=text;else interim+=text}$("#videoTranscript").value=transcriptFinal+interim};recognition.onerror=e=>{const blocked=["not-allowed","service-not-allowed","audio-capture"].includes(e.error);if(blocked)recognitionShouldRun=false;if(e.error!=="aborted")$("#recordingStatus").textContent=blocked?"麦克风权限未开启，视频仍会继续录制":"录制中，语音识别暂时不可用"};recognition.onend=()=>{if(recognitionShouldRun&&mediaRecorder?.state==="recording")setTimeout(()=>{if(recognitionShouldRun&&mediaRecorder?.state==="recording")try{recognition.start()}catch(e){recognitionShouldRun=false}},300)};recognitionShouldRun=true;try{recognition.start()}catch(e){recognitionShouldRun=false;$("#recordingStatus").textContent="语音识别无法启动，视频仍会继续录制"}}else{$("#recordingStatus").textContent="正在录制（当前浏览器不支持自动语音转写）"}startOutput(()=>{if(mediaRecorder?.state==="recording"){mediaRecorder.autoFinish=true;mediaRecorder.stop()}else finish($("#videoTranscript").value)});};$("#finishVideoButton").onclick=()=>finish($("#videoTranscript").value);
$("#downloadSlidesButton").onclick=()=>{const pages=[...$("#slideEditor").querySelectorAll(".slide-page")].map((page,i)=>`<section><p>${i+1}/${$("#slideEditor").querySelectorAll(".slide-page").length}</p>${page.innerHTML.replace(/<small>[\s\S]*?<\/small>|<button[\s\S]*?<\/button>/g,"")}</section>`).join("");const html=`<html lang="zh-CN"><meta charset="utf-8"><title>${currentConcept} 演示稿</title><style>body{font-family:Arial;margin:0;color:#17212b}section{height:100vh;display:grid;place-content:center;padding:0 12vw;background:#f4f6f8}h3{font-size:56px;color:#176851}p{font-size:28px;color:#66717c}</style>${pages}</html>`,a=document.createElement("a");a.href=URL.createObjectURL(new Blob([html],{type:"text/html"}));a.download="finance-presentation.html";a.click()};$("#newPracticeButton").onclick=()=>show("draw");
// Extended timer and local memory features
selectedSeconds=0;outputSeconds=0;
const originalStartTimer=$("#startTimerButton").onclick;$("#startTimerButton").onclick=()=>{const d=selectedHours*3600+selectedMinutes*60+selectedSeconds;if(!d)return;endAt=Date.now()+d*1000;$("#timerRunning").classList.remove("hidden");$(".timer-setup").classList.add("hidden");$("#pauseTimerButton").textContent="暂停";clearInterval(timerId);timerId=setInterval(updateLearn,250);updateLearn()};
const originalStartOutput=startOutput;startOutput=function(onDone){const d=outputHours*3600+outputMinutes*60+outputSeconds;if(!d)return false;outputEnd=Date.now()+d*1000;clearInterval(outputId);outputId=setInterval(()=>{if(outputTick()<=0){clearInterval(outputId);alarm();onDone?.()}},250);outputTick();return true};
const memoryList=document.createElement("section");memoryList.className="memory-section";memoryList.innerHTML='<p class="section-label">往期记忆</p><h3>已完成的练习</h3><div id="memoryList" class="memory-list"><p class="muted">还没有完成的练习。</p></div>';$("#drawStage").append(memoryList);
function refreshMemory(){const list=$("#memoryList"),items=JSON.parse(localStorage.getItem("financePracticeMemory")||"[]");list.innerHTML=items.length?items.map((m,i)=>`<article class="memory-item"><strong>${m.concept}</strong><span>${m.date}</span><p>${m.transcript||"无语音转写"}</p><div class="memory-actions"><button class="secondary-button" data-memory="${i}">查看</button><button class="text-button" data-repeat="${i}">再次练习</button></div></article>`).join(""):"<p class=\"muted\">还没有完成的练习。</p>"}
refreshMemory();
const completePractice=finish;finish=function(text){const record={concept:currentConcept,english:currentEnglish,transcript:text||"",date:new Date().toLocaleString("zh-CN"),video:mediaRecorder?.blobUrl||""};memories=[...memories.filter(m=>m.english!==currentEnglish),record];localStorage.setItem(memoryKey,JSON.stringify(memories));refreshMemory();completePractice(text)};
$("#memoryList").addEventListener("click",e=>{const button=e.target.closest("button[data-memory]");if(!button)return;const item=memories[Number(button.dataset.memory)];if(!item)return;$("#reviewText").value=item.transcript||"（本次录制没有生成语音转写内容）";currentConcept=item.concept;currentEnglish=item.english;renderDeck("#reviewDeckPreview");show("review")});
$("#memoryList").addEventListener("click",e=>{const button=e.target.closest("button[data-repeat]");if(!button)return;const item=memories[Number(button.dataset.repeat)],c=concepts.find(x=>x[0]===item?.english);if(!c)return;currentEnglish=c[0];currentConcept=c[1];$("#conceptEnglish").textContent=c[0];$("#conceptChinese").textContent=c[1];show("learn")});
document.querySelectorAll("[data-stage]").forEach(item=>{item.setAttribute("role","button");item.tabIndex=0;item.addEventListener("click",()=>show(item.dataset.stage));item.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();show(item.dataset.stage)}})});
function addExitButton(stageId){const stage=$(stageId);if(!stage||stage.querySelector(".exit-stage"))return;const button=document.createElement("button");button.type="button";button.className="text-button exit-stage";button.textContent="退出本阶段，返回首页";button.onclick=()=>{clearInterval(timerId);clearInterval(outputId);if(mediaRecorder?.state==="recording")mediaRecorder.stop();recognitionShouldRun=false;recognition?.stop();show("draw")};stage.append(button)}["#learnStage","#outputStage","#reviewStage"].forEach(addExitButton);
const englishText={"退出本阶段，返回首页":"Exit stage and return home","已完成的练习":"Completed practices","往期记忆":"Practice history","还没有完成的练习。":"No completed practices yet.","无语音转写":"No transcript","查看":"View","再次练习":"Practice again","录制完成，语音转写已停止":"Recording complete. Transcription stopped.","正在录制并自动转写...":"Recording and transcribing...","当前浏览器不支持视频录制":"Video recording is not supported in this browser.","无法访问摄像头或麦克风，请检查浏览器权限":"Camera or microphone access was denied. Check browser permissions.","麦克风权限未开启，视频仍会继续录制":"Microphone access is off. Video recording will continue.","录制中，语音识别暂时不可用":"Recording. Speech recognition is temporarily unavailable.","语音识别无法启动，视频仍会继续录制":"Speech recognition could not start. Video recording will continue.","正在录制（当前浏览器不支持自动语音转写）":"Recording. Automatic transcription is not supported in this browser."};
function translateVisibleText(){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);while(walker.nextNode()){let value=walker.currentNode.nodeValue;Object.entries(englishText).forEach(([cn,en])=>{value=value.replaceAll(cn,en)});walker.currentNode.nodeValue=value}document.querySelectorAll("input[placeholder],textarea[placeholder]").forEach(el=>Object.entries(englishText).forEach(([cn,en])=>{el.placeholder=el.placeholder.replaceAll(cn,en)}))}translateVisibleText();new MutationObserver(translateVisibleText).observe(document.body,{subtree:true,childList:true,characterData:true});
