const concepts=[["Money","货币"],["Time Value of Money","货币的时间价值"],["Interest","利息"],["Simple Interest","单利"],["Compound Interest","复利"],["Inflation","通货膨胀"],["Interest Rate","利率"],["Present Value (PV)","现值"],["Future Value (FV)","终值"],["Discount Rate","折现率"],["Investment","投资"],["Return","收益率"],["Risk","风险"],["Risk and Return","风险与收益"],["Asset","资产"],["Stock","股票"],["Bond","债券"],["Dividend","股息"],["Capital Gain","资本利得"],["Portfolio","投资组合"],["Diversification","分散投资"],["Liquidity","流动性"],["Market","市场"],["Supply and Demand","供求关系"],["Bull Market","牛市"],["Bear Market","熊市"],["Market Capitalization","市值"],["Stock Index","股票指数"],["GDP (Gross Domestic Product)","国内生产总值"],["Central Bank","中央银行"]];
const $=id=>document.querySelector(id), stages={draw:$("#drawStage"),learn:$("#learnStage"),output:$("#outputStage"),review:$("#reviewStage")};let selectedHours=0,selectedMinutes=15,outputHours=0,outputMinutes=3,remaining=900,timerId=null,endAt=0,outputId=null,outputEnd=0,mediaRecorder=null,chunks=[],recognition=null,currentConcept="";
function show(name){Object.entries(stages).forEach(([k,e])=>e.classList.toggle("hidden",k!==name));document.querySelectorAll("[data-stage]").forEach(e=>e.classList.toggle("active",e.dataset.stage===name));window.scrollTo({top:0,behavior:"smooth"})}
function alarm(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C();[0,.28,.56,.84,1.12,1.4,1.68,1.96].forEach((d,i)=>{const o=c.createOscillator(),g=c.createGain();o.type="square";o.frequency.value=i%2?1046:880;g.gain.setValueAtTime(.001,c.currentTime+d);g.gain.exponentialRampToValueAtTime(.42,c.currentTime+d+.03);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d+.2);o.connect(g).connect(c.destination);o.start(c.currentTime+d);o.stop(c.currentTime+d+.22)})}
function fmt(s){return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(v=>String(Math.max(0,v)).padStart(2,"0")).join(":")}
function wheel(el,max,val,set){el.innerHTML="";for(let i=0;i<=max;i++){const d=document.createElement("div");d.className="wheel-option"+(i===val?" selected":"");d.textContent=String(i).padStart(2,"0");d.onclick=()=>set(i);el.append(d)}requestAnimationFrame(()=>el.children[val]?.scrollIntoView({block:"center"}));let pending;el.onscroll=()=>{clearTimeout(pending);pending=setTimeout(()=>{const i=Math.min(max,Math.max(0,Math.round(el.scrollTop/44)));if(i!==val){el.querySelectorAll(".wheel-option").forEach(x=>x.classList.remove("selected"));el.children[i].classList.add("selected");set(i)}},120)}}
function renderDeck(target){const editor=$("#slideEditor");if(!editor)return;$(target).innerHTML=[...editor.querySelectorAll(".slide-page")].map((page,i)=>`<article class="slide-mini"><small>第 ${i+1} 页</small>${page.innerHTML.replace(/<button[\s\S]*?<\/button>/g,"")}</article>`).join("")}
function wheels(){wheel($("#hoursWheel"),12,selectedHours,v=>{selectedHours=v});wheel($("#minutesWheel"),59,selectedMinutes,v=>{selectedMinutes=v});wheel($("#outputHoursWheel"),12,outputHours,v=>{outputHours=v;updateOutputPreview()});wheel($("#outputMinutesWheel"),59,outputMinutes,v=>{outputMinutes=v;updateOutputPreview()})}function updateOutputPreview(){const s=outputHours*3600+outputMinutes*60,m=`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;$("#outputCountdown").textContent=m;$("#textCountdown").textContent=m}wheels();updateOutputPreview();
$("#drawButton").onclick=()=>{const c=concepts[Math.floor(Math.random()*concepts.length)];currentConcept=c[1];$("#conceptEnglish").textContent=c[0];$("#conceptChinese").textContent=c[1];renderDeck("#learnSlidePreview");show("learn")};
function finishLearn(){clearInterval(timerId);timerId=null;alarm();show("output")}
function updateLearn(){remaining=Math.max(0,Math.ceil((endAt-Date.now())/1000));$("#countdown").textContent=fmt(remaining);if(remaining<=0)finishLearn()}
$("#startTimerButton").onclick=()=>{const d=selectedHours*3600+selectedMinutes*60;if(!d)return;endAt=Date.now()+d*1000;$("#timerRunning").classList.remove("hidden");$(".timer-setup").classList.add("hidden");$("#pauseTimerButton").textContent="暂停";clearInterval(timerId);timerId=setInterval(updateLearn,250);updateLearn()};
$("#pauseTimerButton").onclick=()=>{if(timerId){clearInterval(timerId);timerId=null;remaining=Math.max(0,Math.ceil((endAt-Date.now())/1000));$("#pauseTimerButton").textContent="继续"}else{endAt=Date.now()+remaining*1000;$("#pauseTimerButton").textContent="暂停";timerId=setInterval(updateLearn,250)}};
$("#resetTimerButton").onclick=()=>{clearInterval(timerId);timerId=null;remaining=selectedHours*3600+selectedMinutes*60;$("#countdown").textContent=fmt(remaining);$("#timerRunning").classList.add("hidden");$(".timer-setup").classList.remove("hidden")};
function outputTick(){const r=Math.max(0,Math.ceil((outputEnd-Date.now())/1000));const m=`${String(Math.floor(r/60)).padStart(2,"0")}:${String(r%60).padStart(2,"0")}`;$("#outputCountdown").textContent=m;$("#textCountdown").textContent=m;return r}
function startOutput(onDone){const d=outputHours*3600+outputMinutes*60;if(!d)return false;outputEnd=Date.now()+d*1000;clearInterval(outputId);outputId=setInterval(()=>{if(outputTick()<=0){clearInterval(outputId);alarm();onDone?.()}},250);outputTick();return true}
function finish(text){clearInterval(outputId);$("#reviewText").value=text||"（本次没有留下文字稿）";renderDeck("#reviewDeckPreview");$("#conceptExplanation").innerHTML=`<p><strong>${currentConcept}</strong> 是本次练习的金融概念。建议从定义、作用机制、现实案例和风险边界四个角度进一步完善理解。</p><p>复习时可以补充：它与哪些概念容易混淆？在实际金融决策中会如何影响判断？</p>`;const length=(text||"").trim().length;$("#presentationFeedback").innerHTML=`<p>本次稿件约 ${length} 个字。</p><p><strong>优点：</strong>已经完成一次完整表达练习，并留下了可回顾的内容。</p><p><strong>改进建议：</strong>尝试先给出一句话定义，再用一个具体例子说明，最后补充一个限制条件或风险点，让结构更完整。</p>`;show("review")}

$("#pptTemplate").onchange=()=>{const t=$("#pptTemplate").value;const pages=$("#slideEditor").querySelectorAll(".slide-page");const sets=t==="compare"?["定义与特征","优势与局限","案例对比"]:["概念定义","核心意义","现实案例"];pages.forEach((p,i)=>{p.querySelector("h3").textContent=sets[i]});renderDeck("#learnSlidePreview")};$("#slideEditor").addEventListener("input",()=>renderDeck("#learnSlidePreview"));$("#slideEditor").addEventListener("click",e=>{if(!e.target.classList.contains("add-text"))return;const p=document.createElement("p");p.contentEditable="true";p.textContent="新增内容";e.target.before(p);p.focus()});$("#addSlideButton").onclick=()=>{const n=$("#slideEditor").querySelectorAll(".slide-page").length+1;const a=document.createElement("article");a.className="slide-page";a.innerHTML=`<small>第 ${n} 页</small><h3 contenteditable="true">新页面标题</h3><p contenteditable="true">点击编辑页面内容。</p><button class="text-button add-text" type="button">+ 添加文本框</button>`;$("#slideEditor").append(a);renderDeck("#learnSlidePreview")};renderDeck("#learnSlidePreview");
$("#videoModeButton").onclick=()=>{$(".mode-choice").classList.add("hidden");$("#videoWorkspace").classList.remove("hidden");$("#textWorkspace").classList.add("hidden");renderDeck("#outputDeckPreview")};$("#textModeButton").onclick=()=>{$(".mode-choice").classList.add("hidden");$("#textWorkspace").classList.remove("hidden");$("#videoWorkspace").classList.add("hidden");renderDeck("#outputDeckPreview")};
$("#startTextButton").onclick=()=>{$("#startTextButton").disabled=true;startOutput(()=>finish($("#textDraft").value));$("#finishTextButton").classList.remove("hidden")};$("#finishTextButton").onclick=()=>finish($("#textDraft").value);
$("#startVideoButton").onclick=async()=>{if(mediaRecorder?.state==="recording"){mediaRecorder.stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){$("#recordingStatus").textContent="当前浏览器不支持视频录制";return}const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});chunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);mediaRecorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());$("#videoPreview").src=URL.createObjectURL(new Blob(chunks,{type:"video/webm"}));$("#videoPreview").classList.remove("hidden");$("#finishVideoButton").classList.remove("hidden");$("#recordingStatus").textContent="录制完成，语音转写已停止";recognition?.stop();if(mediaRecorder.autoFinish)finish($("#videoTranscript").value)};mediaRecorder.start();$("#startVideoButton").textContent="结束录制";$("#recordingStatus").textContent="正在录制并自动转写...";const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(R){recognition=new R();recognition.lang="zh-CN";recognition.continuous=true;recognition.interimResults=true;recognition.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++)$("#videoTranscript").value+=e.results[i][0].transcript};recognition.start()}startOutput(()=>{if(mediaRecorder?.state==="recording"){mediaRecorder.autoFinish=true;mediaRecorder.stop()}else finish($("#videoTranscript").value)});};$("#finishVideoButton").onclick=()=>finish($("#videoTranscript").value);
$("#downloadSlidesButton").onclick=()=>{const pages=[...$("#slideEditor").querySelectorAll(".slide-page")].map((page,i)=>`<section><p>${i+1}/${$("#slideEditor").querySelectorAll(".slide-page").length}</p>${page.innerHTML.replace(/<small>[\s\S]*?<\/small>|<button[\s\S]*?<\/button>/g,"")}</section>`).join("");const html=`<html lang="zh-CN"><meta charset="utf-8"><title>${currentConcept} 演示稿</title><style>body{font-family:Arial;margin:0;color:#17212b}section{height:100vh;display:grid;place-content:center;padding:0 12vw;background:#f4f6f8}h3{font-size:56px;color:#176851}p{font-size:28px;color:#66717c}</style>${pages}</html>`,a=document.createElement("a");a.href=URL.createObjectURL(new Blob([html],{type:"text/html"}));a.download="finance-presentation.html";a.click()};$("#newPracticeButton").onclick=()=>show("draw");
